databases:
  - name: mediplan
    ipAllowList: []
    databaseName: mediplan
    user: linet

services:
  - type: web
    name: mediplan
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mediplan
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false